# Dockerfile for Contextual Retrieval-based CRS ReDial
# Created from CRS implementation in iai-group/iEvaLM-CRS
FROM python:3.9-slim

# Labels
LABEL version="1.0"
LABEL author="IAI group"
LABEL description="Dockerfile for CRB-CRS ReDial"
LABEL type="agent"
LABEL name="CRB_CRS_ReDial"
LABEL tasks=["movie_recommendation"]
LABEL port=5005

WORKDIR /

# Install system-level dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential && \
    rm -rf /var/lib/apt/lists/*

# Install required packages
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy ReDial + MovieLens data
COPY data/redial/ data/redial/
COPY data/redial_eval/ data/redial_eval/
COPY data/movielens/ data//movielens/
COPY data/crb_crs/ data/crb_crs/

# Copy CRB-CRS ReDial checkpoint
COPY data/models/crb_crs_redial data/models/crb_crs_redial

# Copy source code
COPY src/ src/

# Copy execution script
COPY script/serve_model_api.py script/

EXPOSE 5005

CMD ["python", "-m", "script.serve_model_api", "--crs_model", "crbcrs", "--kg_dataset", "redial", "--domain", "movies", "--corpus", "data/redial/corpus", "--mle_model", "data/models/crb_crs_redial/mle_model.pkl", "--rec_model", "data/models/crb_crs_redial/movie_recommender.pkl"]