# Dockerfile for BARCOR OpenDialKG CRS
# Created from CRS implementation in iai-group/iEvaLM-CRS
FROM python:3.9-slim

# Labels
LABEL version="1.0"
LABEL author="IAI group"
LABEL description="Dockerfile for BARCOR OpenDialKG CRS"
LABEL type="agent"
LABEL name="BARCOR_OpenDialKG"
LABEL tasks=["movie_recommendation"]

WORKDIR /

# Install system-level dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential && \
    rm -rf /var/lib/apt/lists/*

# Install required packages
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy OpenDialKG + MovieLend data
COPY data/opendialkg/ data/opendialkg/
COPY data/opendialkg_eval/ data/opendialkg_eval/
COPY data/movielens/ data//movielens/

# Copy BARCOR OpenDialKG checkpoint
COPY data/models/barcor_conv_opendialkg data/models/barcor_conv_opendialkg
COPY data/models/barcor_rec_opendialkg data/models/barcor_rec_opendialkg

# Copy source code
COPY src/ src/

# Copy execution script
COPY ../script/serve_model_api.py script/

CMD ["python", "-m", "script.serve_model_api", "--crs_model", "barcor", "--kg_dataset", "opendialkg", "--context_max_length", "200", "--rec_model","data/models/barcor_rec_opendialkg/", "--conv_model","data/models/barcor_conv_opendialkg/", "--tokenizer_path","facebook/bart-base", "--resp_max_length","128", "--debug"]