# Dockerfile for ChatGPT-based OpenDialKG CRS
# Created from CRS implementation in iai-group/iEvaLM-CRS
FROM python:3.9-slim

# Labels
LABEL version="1.0"
LABEL author="IAI group"
LABEL description="Dockerfile for ChatCRS OpenDialKG"
LABEL type="agent"
LABEL name="ChatCRS_OpenDialKG"
LABEL tasks=["movie_recommendation"]
LABEL port=5005

WORKDIR /

# Install system-level dependencies
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential && \
    rm -rf /var/lib/apt/lists/*

# Install required packages
COPY requirements.txt requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy ReDial + MovieLens data
COPY data/opendialkg/ data/opendialkg/
COPY data/opendialkg_eval/ data/opendialkg_eval/
COPY data/movielens/ data//movielens/
COPY data/embed_items/opendialkg/ data/embed_items/opendialkg/

# Copy source code
COPY src/ src/

# Copy execution script
COPY script/serve_model_api.py script/

EXPOSE 5005

CMD ["python", "-m", "script.serve_model_api", "--kg_dataset", "opendialkg", "--crs_model", "chatgpt"]