"""Flask API to serve the model."""

import json
import logging
import uuid
from typing import Any, Dict, Tuple

import openai
from flask import Flask, Response, request, session

from src.model.CHATGPT import CHATGPT
from src.model.crs_model import CRSModel
from src.model.utils import get_entity, get_options

logging.basicConfig(
    format="[%(asctime)s] %(levelname)-12s %(message)s",
    handlers=[logging.StreamHandler()],
)
logger = logging.getLogger(__name__)


class ModelAPI:
    def __init__(
        self,
        crs_model: CRSModel,
        kg_dataset: str,
        response_generation_args: Dict[str, Any] = {},
    ) -> None:
        """Initializes CRS Flask server.

        Args:
            crs_model: CRS model.
            kg_dataset: Name of knowledge graph dataset.
            response_generation_args: Arguments for response generation.
              Defaults to None.
        """
        self.crs_model = crs_model

        # Load entity data
        with open(
            f"data/{kg_dataset}/entity2id.json", "r", encoding="utf-8"
        ) as f:
            self.entity2id = json.load(f)

        self.id2entity = {int(v): k for k, v in self.entity2id.items()}
        self.entity_list = list(self.entity2id.keys())

        # Get options
        self.options = get_options(kg_dataset)

        # Response generation arguments
        self.response_generation_args = response_generation_args

        self.app = Flask(__name__)
        self.app.add_url_rule(
            "/receive_message",
            view_func=self.receive_message,
            methods=["GET", "POST"],
        )
        self.app.add_url_rule(
            "/configure",
            view_func=self.configure_crs,
            methods=["POST"],
        )
        self.app.secret_key = str(uuid.uuid4().hex)

    def start(self, host: str = "127.0.0.1", port: str = "5005") -> None:
        """Starts the CRS Flask server.

        Args:
            host: Host address. Defaults to 127.0.0.1.
            port: Port number. Defaults to 5005.
        """
        self._host = host
        self._port = port
        self.app.run(host=host, port=port)

    def receive_message(self) -> Tuple[Dict[str, Any], int]:
        """Receives a message and returns a response.

        Returns:
            A response dictionary with the message and status code.
        """
        if request.method == "GET":
            return "Model is running.", 200
        else:
            sender_data = request.get_json()
            logger.debug(f"Received user request:\n{sender_data}")

            try:
                # Process conversation to create conversation dictionary
                conversation_dict = self._process_sender_data(sender_data)
                state = conversation_dict.pop("state")

                # Get response
                response, new_state = self.crs_model.get_response(
                    conversation_dict,
                    self.id2entity,
                    self.options,
                    state,
                    **self.response_generation_args,
                )
                logger.debug(f"Generated response: {response}")
                session["state"] = new_state
                return {"response": response}, 200
            except ValueError as e:
                logger.error(f"Error occurred: {e}")
                return (
                    "An error occurred, make sure you have provided the context"
                    " and message.",
                    400,
                )

    def _process_sender_data(
        self, sender_data: Dict[str, Any]
    ) -> Dict[str, Any]:
        """Processes sender data to create conversation dictionary.

        The conversation dictionary contains the following keys: context,
        entity, rec, resp, template, and state. Context is a list of the
        previous utterances, entity is a list of entities mentioned in the
        conversation, rec is the recommended items, resp is the response
        generated by the model, and state is the state of the options.
        Note that rec, resp, and template are empty as the model is used for
        inference only, they are kept for compatibility with the models.

        Args:
            sender_data: Data sent by the sender.

        Raises:
            ValueError: If context or message is not present in sender data.

        Returns:
            Conversation dictionary.
        """
        if any(key not in sender_data for key in ["context", "message"]):
            raise ValueError(
                "Invalid sender data. Missing context or message."
            )

        context = sender_data["context"] + [sender_data["message"]]

        state = session.pop("state", None)
        if state is None or len(state) != len(self.options[1]):
            state = [0.0] * len(self.options[1])

        entities = []
        for utterance in context:
            utterance_entities = get_entity(utterance, self.entity_list)
            entities.extend(utterance_entities)

        return {
            "context": context,
            "entity": entities,
            "rec": [],
            "resp": "",
            "template": [],
            "state": state,
        }

    def configure_crs(self) -> Response:
        """Configures CRS model with given options.

        Method is used only for ChatGPT model.

        Returns:
            A response with the status code.
        """
        if isinstance(self.crs_model.crs_model, CHATGPT):
            data = request.get_json()
            if "api_key" not in data:
                return Response("API key is required.", status=400)
            openai.api_key = data["api_key"]

        return Response("Agent successfully configured.", status=201)
